/**
 * Project bundles (.sb01.zip): the portable backup and exchange format.
 *
 *   project.json          the Project (validated and migrated on import)
 *   samples/<id>.<ext>    original bytes of every imported recording
 *   README.txt            what the file is and how to open it
 *
 * Built-in sounds are generated by the app and never stored in bundles.
 * Zipping is synchronous (fflate): recordings are stored uncompressed, so only
 * project.json is deflated and even large bundles pack quickly.
 */
import { strFromU8, strToU8, unzipSync, zipSync, type Zippable } from 'fflate';
import { uid } from '../project/factory';
import type { Id, Project, SampleMeta } from '../project/types';
import { validateProject } from '../project/validate';

export const BUNDLE_EXTENSION = '.sb01.zip';
export const BUNDLE_MIME = 'application/zip';
export const BUNDLE_MAX_BYTES = 300 * 1024 * 1024;
/** Upper bound on the uncompressed content we are willing to expand (zip-bomb guard). */
const MAX_EXPANDED_BYTES = 600 * 1024 * 1024;
const PROJECT_FILE = 'project.json';
const SAMPLE_DIR = 'samples/';

export const BUNDLE_README = `SWITCHBOARD / 01 project file
==============================

This zip file is a complete SWITCHBOARD / 01 project: patterns, scenes,
sounds and settings, routing and macros, the song arrangement, recorded
performances, and every recording you imported.

  project.json        the project (plain JSON, schema "switchboard01.project")
  samples/            your imported recordings, as the original files

To open it: in SWITCHBOARD / 01, open the project library, choose Import and
pick this .sb01.zip file. It works in any browser profile, on any computer,
without an internet connection.

Browser storage is working storage; keep project files like this one as your
backup.
`;

const EXT_BY_MIME: Record<string, string> = {
  'audio/wav': 'wav',
  'audio/x-wav': 'wav',
  'audio/wave': 'wav',
  'audio/vnd.wave': 'wav',
  'audio/mpeg': 'mp3',
  'audio/mp3': 'mp3',
  'audio/ogg': 'ogg',
  'audio/flac': 'flac',
  'audio/x-flac': 'flac',
  'audio/aac': 'aac',
  'audio/mp4': 'm4a',
  'audio/webm': 'webm',
};

export function extensionForMime(mime: string): string {
  return EXT_BY_MIME[mime.toLowerCase()] ?? 'bin';
}

/** File name for a sample inside the bundle. Ids are validated to be file-name safe. */
export function samplePath(meta: Pick<SampleMeta, 'id' | 'mime'>): string {
  return `${SAMPLE_DIR}${meta.id}.${extensionForMime(meta.mime)}`;
}

/** A safe download file name for a project. */
export function bundleFileName(project: Pick<Project, 'name'>): string {
  const base = project.name
    .normalize('NFKD')
    .replace(/[^\w\- ]+/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, 60);
  return `${base || 'switchboard-project'}${BUNDLE_EXTENSION}`;
}

export class BundleExportError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'BundleExportError';
  }
}

const MB = 1024 * 1024;

/**
 * Pack a project and its imported recordings. Rejects (BundleExportError)
 * when a recording the project lists cannot be found, or when the file would
 * be larger than importBundle accepts, rather than writing a backup that
 * cannot be opened again.
 */
export async function exportBundle(project: Project, getSampleBlob: (id: Id) => Promise<Blob | null>): Promise<Blob> {
  const json = strToU8(JSON.stringify(project, null, 2));
  const files: Zippable = {
    [PROJECT_FILE]: [json, { level: 6 }],
    'README.txt': [strToU8(BUNDLE_README), { level: 6 }],
  };
  // Recordings are stored uncompressed, so their sizes (plus the JSON, which
  // only shrinks when deflated) bound the size of the zip.
  let total = json.byteLength;
  for (const meta of project.samples) {
    const blob = await getSampleBlob(meta.id);
    if (!blob) throw new BundleExportError(`The recording "${meta.name}" is missing from this browser's storage, so the project file would be incomplete.`);
    total += blob.size;
    if (total > BUNDLE_MAX_BYTES) {
      throw new BundleExportError(
        `This project's recordings add up to more than the ${BUNDLE_MAX_BYTES / MB} MB a project file can hold. Remove recordings the project no longer needs, then export again.`,
      );
    }
    // Audio is already dense (or compressed); store it without deflating.
    files[samplePath(meta)] = [new Uint8Array(await blob.arrayBuffer()), { level: 0 }];
  }
  const zipped = zipSync(files);
  if (zipped.byteLength > BUNDLE_MAX_BYTES) {
    throw new BundleExportError(`This project file would be larger than the ${BUNDLE_MAX_BYTES / MB} MB limit. Remove recordings the project no longer needs, then export again.`);
  }
  return new Blob([zipped], { type: BUNDLE_MIME });
}

export interface ImportedSample {
  meta: SampleMeta;
  blob: Blob;
}

export type ImportBundleResult =
  | { ok: true; project: Project; samples: ImportedSample[]; warnings: string[] }
  | { ok: false; error: string };

export interface ImportBundleOptions {
  /** Give the project a new id so it is added alongside (not over) an existing copy. */
  newId?: boolean;
}

function isZip(bytes: Uint8Array): boolean {
  // Local file header "PK\x03\x04", or an empty archive "PK\x05\x06".
  return bytes.length >= 4 && bytes[0] === 0x50 && bytes[1] === 0x4b && ((bytes[2] === 3 && bytes[3] === 4) || (bytes[2] === 5 && bytes[3] === 6));
}

/**
 * Read a project bundle. Validates and migrates the project, checks that
 * every imported recording the project refers to is present, and returns
 * readable errors for anything else. Never throws.
 */
export async function importBundle(file: Blob, opts: ImportBundleOptions = {}): Promise<ImportBundleResult> {
  try {
    if (file.size > BUNDLE_MAX_BYTES) return { ok: false, error: `This file is larger than the ${BUNDLE_MAX_BYTES / MB} MB limit for project files.` };
    if (file.size === 0) return { ok: false, error: 'This file is empty.' };
    const bytes = new Uint8Array(await file.arrayBuffer());
    if (!isZip(bytes)) return { ok: false, error: `This is not a SWITCHBOARD project file. Choose a ${BUNDLE_EXTENSION} file exported from SWITCHBOARD.` };

    let expanded = 0;
    let tooBig = false;
    let entries: Record<string, Uint8Array>;
    try {
      entries = unzipSync(bytes, {
        filter: (f) => {
          const wanted = f.name === PROJECT_FILE || (f.name.startsWith(SAMPLE_DIR) && !f.name.endsWith('/'));
          if (!wanted) return false;
          expanded += f.originalSize;
          if (expanded > MAX_EXPANDED_BYTES) tooBig = true;
          return !tooBig;
        },
      });
    } catch {
      return { ok: false, error: 'This project file is damaged and could not be opened.' };
    }
    if (tooBig) return { ok: false, error: 'This project file expands to more data than SWITCHBOARD can open.' };

    const json = entries[PROJECT_FILE];
    if (!json) return { ok: false, error: 'This zip file does not contain a SWITCHBOARD project (project.json is missing).' };
    let raw: unknown;
    try {
      raw = JSON.parse(strFromU8(json));
    } catch {
      return { ok: false, error: 'The project inside this file is damaged (project.json is not valid JSON).' };
    }
    const v = validateProject(raw);
    if (!v.ok) return { ok: false, error: `This project file cannot be opened: ${v.errors[0]}` };
    const project = v.project;
    const warnings = [...v.warnings];

    // Index sample files by id (the part of the file name before the extension).
    const byId = new Map<string, Uint8Array>();
    for (const [name, data] of Object.entries(entries)) {
      if (!name.startsWith(SAMPLE_DIR)) continue;
      const base = name.slice(SAMPLE_DIR.length);
      const dot = base.lastIndexOf('.');
      byId.set(dot > 0 ? base.slice(0, dot) : base, data);
    }

    const inUse = new Set<Id>();
    const collect = (tracks: Project['tracks']) => {
      for (const t of tracks) if (t.instrument.kind === 'sampler' && t.instrument.sampleId && !t.instrument.sampleId.startsWith('builtin:')) inUse.add(t.instrument.sampleId);
    };
    collect(project.tracks);
    for (const perf of project.performances) collect(perf.snapshot.tracks);

    const samples: ImportedSample[] = [];
    const keptMeta: SampleMeta[] = [];
    for (const meta of project.samples) {
      const data = byId.get(meta.id);
      if (!data) {
        if (inUse.has(meta.id)) return { ok: false, error: `The recording "${meta.name}" is missing from this project file, so it cannot be opened completely.` };
        warnings.push(`The unused recording "${meta.name}" was missing from the file and was left out.`);
        continue;
      }
      const m: SampleMeta = { ...meta };
      if (m.byteLength !== data.byteLength) m.byteLength = data.byteLength;
      keptMeta.push(m);
      samples.push({ meta: m, blob: new Blob([data as Uint8Array<ArrayBuffer>], { type: meta.mime }) });
    }
    project.samples = keptMeta;
    if (opts.newId) project.id = uid('proj');
    return { ok: true, project, samples, warnings };
  } catch (e) {
    return { ok: false, error: `This project file could not be opened (${e instanceof Error ? e.message : 'unexpected error'}).` };
  }
}
