/**
 * Offline caching (service worker) with visible readiness/update states.
 *
 * A new version opens by itself unless a page is in use. When a new version
 * installs (a new download started at the same address), its service worker
 * (public/sw-takeover.js) asks every open page "omni:busy?". A page answers
 * "busy" once it has been used: a key or the pointer pressed in it since it
 * loaded, playback (also paused), a recording, or an export running.
 * Otherwise it answers "idle".
 * - No page busy: the new version activates and each page reloads into it.
 * - A page busy: the new version waits, and the ⋯ menu offers Update (which
 *   waits for playback and recordings to stop, see OfflineStatus). A page in
 *   use is never reloaded under the person: when another page applies the
 *   update, it keeps running and offers Update too. A waiting version is
 *   asked to try again whenever a page loads, so a refresh helps once nothing
 *   else is in use.
 * Pages from 2.2 and earlier cannot answer; the service worker reloads them.
 *
 * The state lives in runtime.ts (offlineStore); the transport's OfflineStatus
 * shows it. Only main.tsx loads this module, because the service-worker
 * registration is generated by the build. Loading it starts listening, so
 * the page answers even before the app has finished starting.
 */
/// <reference types="vite-plugin-pwa/client" />
import { registerSW } from 'virtual:pwa-register';
import { session } from './instance';
import { offlineStore, runtimeStore } from './runtime';

export { offlineStore, useOffline, type OfflineState } from './runtime';

const supported = typeof window !== 'undefined' && 'serviceWorker' in navigator && window.isSecureContext;

/** A key or the pointer was pressed in this page since it loaded. */
let used = false;
/** This page applied the update (Update): it reloads when the new version takes over. */
let requested = false;
let reloading = false;

/** Whether reloading now would interrupt the person (see the module comment). */
function inUse(): boolean {
  const rt = runtimeStore.getState();
  return used || rt.playing || rt.paused || rt.recording !== 'off' || rt.countingIn || session.exporting;
}

function reload(): void {
  if (reloading) return;
  reloading = true;
  window.location.reload();
}

if (supported) {
  const mark = () => {
    used = true;
  };
  window.addEventListener('pointerdown', mark, { capture: true, once: true });
  window.addEventListener('keydown', mark, { capture: true, once: true });

  // A new version's question, answered on the channel it sent.
  navigator.serviceWorker.addEventListener('message', (e) => {
    if (e.data === 'omni:busy?' && e.ports[0]) e.ports[0].postMessage(inUse() ? 'busy' : 'idle');
  });

  // The version this page runs under; null on a first visit (none installed yet).
  let controller = navigator.serviceWorker.controller;
  navigator.serviceWorker.addEventListener('controllerchange', () => {
    const replaced = controller !== null;
    controller = navigator.serviceWorker.controller;
    // The first install took this page over: it already shows that version.
    if (!replaced) return;
    if (requested || !inUse()) {
      reload();
      return;
    }
    // In use: the new version is active, and this page shows the earlier one until Update.
    offlineStore.setState({ state: 'update-ready', apply: reload });
  });
}

export function registerServiceWorker(): void {
  if (!supported) return;
  offlineStore.setState({ state: 'installing', apply: null });
  const update = registerSW({
    immediate: true,
    onOfflineReady() {
      offlineStore.setState({ state: 'ready', apply: null });
    },
    onNeedRefresh() {
      // A new version waits: a page was in use when it installed.
      offlineStore.setState({
        state: 'update-ready',
        apply: () => {
          requested = true;
          void update(true);
        },
      });
    },
    // Whether to reload when a new version takes over is decided above (controllerchange).
    onNeedReload() {},
    onRegisteredSW(_url, reg) {
      // Already controlling the page from an earlier visit: offline is ready.
      if (reg?.active && navigator.serviceWorker.controller) offlineStore.setState((s) => (s.state === 'installing' ? { ...s, state: 'ready' } : s));
      // A new version was left waiting by a page in use: it takes over now if no page is in use.
      reg?.waiting?.postMessage({ type: 'OMNI_TAKE_OVER_IF_IDLE' });
    },
    onRegisterError() {
      offlineStore.setState({ state: 'error', apply: null });
    },
  });
}
