/**
 * Offline caching (service worker) with visible readiness/update states.
 * Updates are never applied automatically: the user reloads when ready, so a
 * performance is never interrupted.
 *
 * The state lives in runtime.ts (offlineStore); the transport's OfflineStatus
 * shows it. Only main.tsx loads this module, because the service-worker
 * registration is generated by the build.
 */
/// <reference types="vite-plugin-pwa/client" />
import { registerSW } from 'virtual:pwa-register';
import { offlineStore } from './runtime';

export { offlineStore, useOffline, type OfflineState } from './runtime';

export function registerServiceWorker(): void {
  if (!('serviceWorker' in navigator) || !window.isSecureContext) return;
  offlineStore.setState({ state: 'installing', apply: null });
  const update = registerSW({
    immediate: true,
    onOfflineReady() {
      offlineStore.setState({ state: 'ready', apply: null });
    },
    onNeedRefresh() {
      offlineStore.setState({ state: 'update-ready', apply: () => void update(true) });
    },
    onRegisteredSW(_url, reg) {
      // Already controlling the page from an earlier visit: offline is ready.
      if (reg?.active && navigator.serviceWorker.controller) offlineStore.setState((s) => (s.state === 'installing' ? { ...s, state: 'ready' } : s));
    },
    onRegisterError() {
      offlineStore.setState({ state: 'error', apply: null });
    },
  });
}
